authors:
  peterkozak:
    name: Peter Kozak
    description: CTO, Cloudficient
    avatar: https://github.com/identicons/cfpeterkozak.png
  brandondagostino:
    name: Brandon D'Agostino
    description: VP, Cloudficient
    avatar: https://github.com/identicons/brandondagostino.png
