authors:
  peterkozak:
    name: Peter Kozak
    description: CTO, Cloudficient
    avatar: images/authors/peter-kozak.jpg
  brandondagostino:
    name: Brandon D'Agostino
    description: VP, Cloudficient
    avatar: images/authors/brandon-dagostino.jpg
